version: '3.8'

services:
    client:
        build: 
            context: .
            dockerfile: Dockerfile
        image: betuah/sthing_client:release
        container_name: sthing_client
        ports:
            - 5000:8080